name: All Detections Forwading to Elastic

on:
  push:
    path:
      - '**.toml'
  workflow_dispatch:

jobs:
  elastic-detection-all:
    runs-on: ubuntu-latest
    env:
    ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'
      - run: pip install requests
      - run: python development/toml_to_json.py
      
