name: TOML/MITRE Validation

on:
  workflow_dispatch:

jobs:
  toml_validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'
      - run: pip install requests
      - run: python development/validation.py
      - run: python development/mitre.py
